import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Your Application Online</title>
        <meta name="description" content="Generated by create Maliek Galant" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://adball.tech">Maliek Galant's Blog</a>
        </h1>

        <p className={styles.description}>
          Get started by coding and editing{' '}
          <code className={styles.code}>Pages/Index.js</code>
          <code className={styles.code}>Pages/Adsense.js</code>

        </p>

        <div className={styles.grid}>
          <a href="https://adball.tech/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://adball.tech/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://www.adball.online/new?utm_source=create-app&utm_medium=default-template&utm_campaign=create-app"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
          <a href="https://adball.tech/learn" className={styles.card}>
            <h2>Contact Us &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
           <a href="https://adball.tech/learn" className={styles.card}>
            <h2>About Us &rarr;</h2>
            <p>Learn about how I made my interactive apps with quizzes!</p>
          </a>
          <a href="https://adball.tech/learn" className={styles.card}>
            <h2>Privacy Policy &rarr;</h2>
            <p>Learn about Maliek's Blog privacy policy in an way to understand your rights!</p>
          </a>
          <a href="https://adball.tech/learn" className={styles.card}>
            <h2>Terms Of Use &rarr;</h2>
            <p>Learn about Maliek's Blog in professional terms </p>
          </a>
          <a href="/amp.js" className={styles.card}>
            <h2>Don't Sell My Information &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          ©️ by Maliek Galant {' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />


          </span>
        </a>
      </footer>
    </div>
  );
}
